<?php

	require_once("mail_service.php");
	require_once("db_config.php");

	isExist = false;

    if($_POST["email"] == NULL){
        $user_name = mysqli_real_escape_string($db, $_POST["username"]);
        $query = "SELECT * FROM sodexo-member WHERE username = '$user_name'";
    }
	else if($_POST["username"] == NULL){
        $user_email = mysqli_real_escape_string($db, $_POST["email"]);
        $query = "SELECT * FROM sodexo-member WHERE email = '$user_email'";
    }
	
	
	
	$result = mysqli_query($db, $query);
	$count = mysqli_num_rows($result);
	switch ($count) {
		case 0:
			echo json_encode(array("state"=>"fail", "msg"=>"user_not_exist"));
			break;
		case 1:
			isExist = true;
			$row = mysqli_fetch_array($result, MYSQLI_ASSOC);
			$user_email = $row["email"];
			$user_name = $row["username"];
			break;
		case 2:
            		echo json_encode(array("state"=>"fail", "msg"=>"multiple_users_matched"));
			break;
	}
	
	if(isExist){
		//Set sender and recipient
		$mail->setFrom("admin@admin.com", "Admin"); //Is there any email address to let us send email?
		$mail->addAddress($user_email);

		//Set content of the email
		$mail->Subject = "Password Reset Request";
		$mail->Body = "User(\"".$user_name."\") is requesting for a password reset. Please click the following link to reset the password. ";
    //link need to be generated by us, to be added later
		$mail->send();

		echo json_encode(array("state"=>"success"));
	}
	
?>
